before_script: cd demo
language: java
jdk:
  - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "fxrobin" # the key of the org you chose at step #3
    
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
